### ISSUE TITLE
Runtime Support for Node.js 16

### ISSUE THREAD

**Issue by melanahammel** [awslabs/amazon-app-runner-deploy#10]
Currently the [only supported runtime for Node.js](https://github.com/awslabs/amazon-app-runner-deploy/blob/main/action.yml#L26) is Node.js 12. With Node.js 12 in maintenance mode, are there plans to support active versions including Node.js 16?

**Comment by gsogol** [comment]
Very much needed

**Comment by Serginyo90** [comment]
Need it
