### ISSUE TITLE
Action to fail when deployment fail and is rolled back

### ISSUE THREAD

**Issue by kristoffertorstad** [awslabs/amazon-app-runner-deploy#11]
Description: 
Current behavior does not catch when deployment fail but successfully recover to previous version. 

Current behavior:
Action uses build from repository or ECR, updates service and waits for status !== operation_in_progress.

Suggested behavior:
Action should store OperationID on updateServiceCommand() and then poll that operation until status !== operation_in_progress. Then return success on status == succeded or else fail

**Comment by hariohmprasath** [comment]
Hi @kristoffertorstad,
Thanks for bringing this up to our attention. Do you want to submit a PR  with the suggested changes? would love to take you in as a contributor.

**Comment by kristoffertorstad** [comment]
Thanks for the fast reply, would love to contribute! I have submitted a early draft PR. Haven't much experience with GH Actions from before, and not sure how I should go about proper testing.

**Comment by hoang-van-nhat** [comment]
Any update on this issue?

**Comment by suzu-prog** [comment]
Hi, I need this.

**Comment by yyamanoi1222** [comment]
No progress on the submitted PR, so I'll start this issue.
