### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by yyamanoi1222** [awslabs/amazon-app-runner-deploy#21]
To manage resources with tags

**Comment by brandonrobertz** [comment]
This is pretty important functionality, would be cool to see it merged or something similar adopted. Specifically, it would be good to be able to tag deployed resources with the name of the GH repo it originated from.

**Comment by yyamanoi1222** [comment]
@DmitryGulin 
If you have no problem with implementing this feature, I will submit a PR.

**Comment by hariohmprasath** [comment]
Hi @yyamanoi1222 
We would love to take in your contribution, please go ahead and submit a PR. Thanks

**Comment by DmitryGulin** [comment]
> @DmitryGulin If you have no problem with implementing this feature, I will submit a PR.

Hi @yyamanoi1222 
Absolutely, go ahead and create a new PR.
The only problem with the first one was that you created it during the major refactoring process. Thank you so much!
