### ISSUE TITLE
Failed to assume instance-role-arn

### ISSUE THREAD

**Issue by pjoshi-cs** [awslabs/amazon-app-runner-deploy#43]
I followed the README and https://aws.amazon.com/blogs/containers/deploy-applications-in-aws-app-runner-with-github-actions/  documentation to implement GitHub action flow for image-based service. I am also successfully able to implement copy-env-vars. While implementing `copy-secret-env-vars` first it errored about not including `instance-role-arn`. I tried to follow a similar approach to create a role with SSM Read Only access and used that ARN as `instance-role-arn`. But it failed with error `Failed to assume instance-role-arn`.

Trusted Policy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ssm.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}

Permission: (AmazonSSMReadOnlyAccess)
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ssm:Describe*",
                "ssm:Get*",
                "ssm:List*"
            ],
            "Resource": "*"
        }
    ]
}

How to resolve this issue or what is the correct role should be used with instance-role-arn?

**Comment by DmitryGulin** [comment]
Hi @pjoshi-cs ,
Your role declares SSM service `ssm.amazonaws.com`, not AppRunner `tasks.apprunner.amazonaws.com` (!!!), as a trusted entity for the role.
Please refer to [App Runner IAM roles | Instance role](https://docs.aws.amazon.com/apprunner/latest/dg/security_iam_service-with-iam.html#security_iam_service-with-iam-roles-service.instance) chapter for the proper Trust Policy definition.
